apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-jzxotgrv
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-jzxotgrv:3c4c991495b1006ef6f8fac55096eb9625cf6881@sha256:ca60202e34a16e0f6a569c6432bdd3b1ddab2bb0a5443f7e2e3e71b43cdb8f5c
        name: container-image  
